### ISSUE TITLE
Search results in utopian.team

### ISSUE THREAD

**Issue by anilkilic** [wehmoen/utopian.team#1]
That's a great idea to put together all the stuff there, thanks @wehmoen.

The problem I encountered was for example;

When I search for *emrebeyler* I get result. 
https://utopian.team/search?q=emre
![Screen Shot 2018-01-07 at 23.39.21.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515357635/r4kw6rsw40e3oinljjz7.png)

---

But when I search for _damla_, she doesn't return under accounts.
https://utopian.team/search?q=damla
![Screen Shot 2018-01-07 at 23.40.55.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515357679/wo4aswa5tcojflhzonls.png)

I personally use this website as if I need to find out moderator's supervisor. So in this case, searching is not helping. 

(quick suggestion, listing moderator names under supervisor on homepage could help.)

Safari Version 11.0.2
macOS Sierra 10.12.6

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@oups/search-results-in-utopian-team">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wehmoen** [comment]
Fixed this in https://github.com/wehmoen/utopian.team/commit/955dab72d146658b1734888080de9a9cda8d9160 :)
